travis:
  secure:
    BINSTAR_TOKEN: rhAZvoL8bTHxTXXA4WHBbKk4ESWGcE2w1VK06EVXCPLt9QYuTLKDPA/c8X3XZctoCDGhEzZdC8RQqVIFzXw7LqhEKm32GiOcGjHscxfiUM3MAQ64rFdJiao8ExhgiFEYAH71C9wg+7ni2ybfHOPQ6x7u9o0QWQgYK7fBdsRzgYUsYJl5xTtXIo15g4IZV/No2M0cNMwi2ka5SqZ+EfAhHtMg7MQPMDmzLnCIz+Me4EmspfOfm/wN3pN0ekMFf7fKsDyh2xBdcq3r5Vhn+RuDwu9ka1LfP/NDyS1QM5574wg3bb40sBEcyPlZcDSfCVNSou7MgPoqIInrrZqtM6yk8p/NT5U5mbrNEMAtSBiefLKZUK6+n9BvoeOinJQa7OWciatugwKdcPEjXgjkx8pvllKC1QRJX78Qn8SAn69wrMnjkLXNfH9BqKms9p2gM88jyVaUdHVCkb96LZQm847CXniC5HyK+ZFQACM9kumdsD8INgyV7+6mwWLNtO7D1PhS8bBiwWX+Loqf0m0uV5No/bxPoDTZVRH+PNnh0UiTO92rZc67S3Sd9DMQhAG1b4Oi+lh098J4C+W/XfKuD2mypwfHmSgtckt9jNCx7WhUnHcWT/S6QXqaez/7YTA5dBdtPfd5ZI8MLqqVlW6C8JidiBt0kNp0DwaUv+XmVAXa+0w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
